### ISSUE TITLE
Create an improved Ethereum API interface

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#102]
Currently the ethereum API interface is very simple (sendTransaction, callView, deployContract). We should expand upon this to reach parity with something like Ethers.js.

**Comment by namesty** [comment]
Friends, I am seeing no one has taken this one since I dropped it. I finished the other ones I was working on. Can I take this one back? @dOrgJelli

**Comment by dOrgJelli** [comment]
Sure thing @namesty!
