### ISSUE TITLE
Support GraphQL Enums

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#107]
Currently, Web3API schemas do not support Enums. An example use-case we'd like to support is:
```graphql
 enum ResponseType {
    TEXT
    BINARY
}

type Request {
    ...
    responseType: ResponseType!
    ...
}
```

**Comment by mpetrun5** [comment]
Different type same problems :cry: 
Currently we parse objects as not scalars eg. is IsScalarType is false we assume it is an object.
This creates a bit of a problem as we now don't know if it is an object or an enum.
One way is to run extractEnumTypes first, but this will create the same problem we had before
we predefined scalars. It will create dependecy between extractors thus blocking #136.

**Comment by dOrgJelli** [comment]
@mpetrun5 I think that we can solve this by doing a "first pass" where we gather all the type names of the Objects & Enums that are defined. We can then check this collection when inferring what a property is.

**Comment by dOrgJelli** [comment]
Basically I think we can define some subset of metadata that's required, and gather it quickly, without doing a "full" extraction of ObjectTypeDefinitions.

**Comment by mpetrun5** [comment]
In schema bind we have a bit of a problem as well as we currently have `toWasmInit` and `toGraphqlType` that also choose objects as not scalars. 
Only way I see to write for all types is to create mustache template that has logic for all types and use that instead of functions as mustache functions afaik can only pass strings.

@dOrgJelli Any ideas?

**Comment by dOrgJelli** [comment]
So the way I'm thinking about this is...
1. Make `enum` another base type, alongside: `scalar`, `array`, and `object`. This will require defining another property for it within TypeInfo.
2. When toGraphQLType runs, we need a way to differentiate between Objects & Enums. I'm thinking we accomplish this by adding `enum ` before the enum's type name. So if you had `enum MyValues { ... }`, calling toGraphQLType would return `enum MyValues`.

This will allow functions like "toWasm" to check to see if it has `enum ` before it and act accordingly. In the future, we'll need to do the same thing for `input` and `interface` types if we choose to support them (nothing planned as of right now).

**Comment by mpetrun5** [comment]
> So the way I'm thinking about this is...
> 
> 1. Make `enum` another base type, alongside: `scalar`, `array`, and `object`. This will require defining another property for it within TypeInfo.
> 2. When toGraphQLType runs, we need a way to differentiate between Objects & Enums. I'm thinking we accomplish this by adding `enum ` before the enum's type name. So if you had `enum MyValues { ... }`, calling toGraphQLType would return `enum MyValues`.
> 
> This will allow functions like "toWasm" to check to see if it has `enum ` before it and act accordingly. In the future, we'll need to do the same thing for `input` and `interface` types if we choose to support them (nothing planned as of right now).

1. Already have parse and compose ready with enum as new base type, but I created branch from objects branch as I needed the new compose and parse refactor so I wait with creating PR until that is finished
EDIT: forgot that parse and compose is already in prealpha-dev will open now

2. That should work :smile:
