### ISSUE TITLE
Don't Support Union Types in GraphQL

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#108]
Add validation logic that throws an error if a union type is used. For example:
```graphql
type Foo {
  prop: String! | UInt8!
}
```

**Comment by namesty** [comment]
@dOrgJelli can I have this one? I can get this done pretty quickly

**Comment by morrigan** [comment]
> @dOrgJelli can I have this one? I can get this done pretty quickly

Hey, we've already talked about this one with Jordan for the next month's proposal. However, we are fine either way :)

**Comment by dOrgJelli** [comment]
Hey @namesty, @morrigan and NodeFactory did talk about taking this issue a while ago, we just forgot to update the Assignees.

**Comment by mpetrun5** [comment]
Is this already resolved by #139? @namesty @dOrgJelli

**Comment by dOrgJelli** [comment]
Yep that's correct @mpetrun5:
https://github.com/Web3-API/monorepo/blob/db6f20cba3eceb630d91968c18b6fd0bccdd139a/packages/schema/parse/src/validate/types.ts#L56-L62
