### ISSUE TITLE
Schema Sanitization

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#61]
Ensure the following scenarios can be detected and properly reported:
- [x] Schema import namespace collisions
- [x] Type name collisions (post import + namespacing)
- [x] Unrecognized directives
- [x] Incorrect directive usage
- [x] Import directive must be on Schema or Mutation type
- [x] No underscores in user defined type names

**Comment by Remscar** [comment]
Happens inside of the web3 build command

**Comment by Remscar** [comment]
```
// What we actually want

// Web3API Query Schema
#import { Query } in Ethereum from "v1.ethereum.web3api.eth"

// Processed Query Schema
type Ethereum_Query @imported(
  namespace: "Ethereum",
  type: "Query",
  uri: "uri.eth"
) {
  ...
}

type Ethereum_Transaction @import_dep(
  ?
) {

}

type Query @imports(
  types: [ "Ethereum_Query" ]
) {
  ...
}

// Processed Combined Schema

all of above + mutation schema
```
