### ISSUE TITLE
Support Object Types as Method Arguments & Return Types

### ISSUE THREAD

**Issue by dOrgJelli** [Web3-API/monorepo#89]
Support:
```graphql
type Query {
  method(arg: CustomType!): CustomType!
}

type CustomType {
  ...
}
```

In order to implement this, we must (roughly speaking):
- Add support for this in the TypeInfo object model (schema-parse package)
- Add support in the extract/query-types visitor (schema-parse package)
- Decide what the generated code will look like (schema-bind package)
- Create a test case to make sure it works (schema-bind package)
- When importing a query type, also import all required object types that are used as arguments or return types (schema-compose package)

**Comment by mpetrun5** [comment]
Hi,

new to this project and started working on parse end of this issue.

To add suport for Object Types can I add object field to `AnyDefinition` and thus to `PropertyDefinition` and then I handle the 3 cases (array, scalar, object) in mustache serialize/deserialize?

**Comment by dOrgJelli** [comment]
Yes I think that sounds like the right approach @mpetrun5

**Comment by dOrgJelli** [comment]
This is currently supported in both the Parse & Compose projects. Just need to implement Bind and we should be good to go :clap:

**Comment by dOrgJelli** [comment]
Started implementing this here @mpetrun5:
https://github.com/Web3-API/prototype/tree/prealpha-dev_bind-nested-obj-types
